### ISSUE TITLE
Unexpected error fetching Opower data: unsupported operand type(s) for +=: 'float' and 'NoneType'

### ISSUE THREAD

**Issue by mrpedaling** [tronikos/opower-hacs#4] opened 2023-05-12 20:31 UTC
Hi, login successful, but warnings and errors on fetch:

```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 258, in _async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/opower/coordinator.py", line 69, in _async_update_data
    await self._insert_statistics([forecast.account for forecast in forecasts])
  File "/config/custom_components/opower/coordinator.py", line 124, in _insert_statistics
    cost_sum += cost_read.provided_cost
TypeError: unsupported operand type(s) for +=: 'float' and 'NoneType'
```

Hope this is helpful. Let me know if I can provide more info, and what kind.

**Comment by tronikos** [comment] 2023-05-12 21:05
Can you log the cost_read?

Change /config/custom_components/opower/coordinator.py line 124 from:
```
                cost_sum += cost_read.provided_cost
```

to
```
                if cost_read.provided_cost is None:
                    _LOGGER.error("cost_read: %s", cost_read)
                cost_sum += cost_read.provided_cost
```

**Comment by mrpedaling** [comment] 2023-05-13 16:02
Thanks for the snippet. Here's that new log output:

Logger: custom_components.opower.coordinator
Source: custom_components/opower/coordinator.py:69 
Integration: Opower (documentation, issues) 
First occurred: 8:56:36 AM (5 occurrences) 
Last logged: 8:58:41 AM
`
cost_read: CostRead(start_time=datetime.datetime(2016, 5, 23, 0, 0, tzinfo=datetime.timezone(datetime.timedelta(days=-1, seconds=61200))), end_time=datetime.datetime(2016, 5, 31, 0, 0, tzinfo=datetime.timezone(datetime.timedelta(days=-1, seconds=61200))), consumption=-99.387, provided_cost=None)`

**Comment by mrpedaling** [comment] 2023-05-13 16:04
Seeing the negative consumption, it just occurred to me to mention we have a grid-tied solar setup w/ net metering.

**Comment by tronikos** [comment] 2023-05-13 21:49
If you login on pge.com and navigate to energy usage details -> energy costs, what do you see? Do you see zero dollars? Or negative dollars?

**Comment by mrpedaling** [comment] 2023-05-14 17:05
I'm seeing negative dollars

**Comment by tronikos** [comment] 2023-05-16 19:00
- In your browser open developer tools and switch to the network tab
- Login to pge.com
- Navigate to energy usage details -> energy costs
-  The second last request should be something like: `https://pge.opower.com/ei/edge/apis/DataBrowser-v1/cws/cost/utilityAccount/XXX?startDate=2023-05-03T00%3A00-0700&endDate=2023-06-01T00%3A00-0700&aggregateType=day&includePtr=false`

Can you copy one of the cost reads with negative value?
e.g. mine (with positive value) is:
```
{
  "startTime": "2023-05-03T00:00:00.000-07:00",
  "endTime": "2023-05-04T00:00:00.000-07:00",
  "value": 13.7592,
  "readType": "ACTUAL",
  "providedCost": 4.258622698,
  "readComponents": [
    {
      "tierType": "ORDINAL",
      "tierNumber": 2,
      "season": "WINTER",
      "dayPart": "OFF_PEAK",
      "cost": 0,
      "value": 0
    },
    {
      "tierType": "ORDINAL",
      "tierNumber": 1,
      "season": "WINTER",
      "dayPart": "OFF_PEAK",
      "cost": 3.31926771,
      "value": 10.8526
    },
    {
      "tierType": "ORDINAL",
      "tierNumber": 1,
      "season": "WINTER",
      "dayPart": "ON_PEAK",
      "cost": 0.939354988,
      "value": 2.9066
    },
    {
      "tierType": "ORDINAL",
      "tierNumber": 2,
      "season": "WINTER",
      "dayPart": "ON_PEAK",
      "cost": 0,
      "value": 0
    }
  ],
  "isPeakPeriod": false,
  "rebateAmount": 0,
  "milesDriven": 23
}
```

**Comment by FrancoisHuet** [comment] 2023-06-10 21:09
FWIW, I tried to reproduce this issue after submitting #6 (which doesn't seem related, thought it's PG&E and I'm also on NEM), but couldn't.

**Comment by tronikos** [comment] 2023-06-30 22:23
Can you still reproduce this? I got PTO for solar a couple of weeks ago and I cannot reproduce. I'm closing this but please reopen if you still experience this.

**Comment by rianadon** [comment] 2023-07-01 21:56
Thank you for the integration @tronikos! I'm really looking forward to getting PG&E data into Home Assistant.

After the setup today of version 0.0.12 I have this same error message, except while we do have solar the consumption for this reading is positive:

`
CostRead(start_time=datetime.datetime(2011, 11, 5, 0, 0, tzinfo=datetime.timezone(datetime.timedelta(days=-1, seconds=61200))), end_time=datetime.datetime(2011, 12, 1, 0, 0, tzinfo=datetime.timezone(datetime.timedelta(days=-1, seconds=57600))), consumption=412.0, provided_cost=None)
`

Any ideas why there is no cost data? Maybe it's just too far back in time?

**Comment by tronikos** [comment] 2023-07-02 05:19
Before I treat missing provided_cost as 0, could you follow my previous messages?

If you login on pge.com and navigate to energy usage details -> energy costs, what do you see for the same time period?

Could you copy the response of one of the relevant `https://pge.opower.com/ei/edge/apis/DataBrowser-v1/cws/cost/utilityAccount/XXX` request?

**Comment by rianadon** [comment] 2023-07-02 19:49
I took a look at the PG&E energy costs dashboard for that time period and it looks like they are for some reason missing the data. There are no cost readings between November of 2011 and August of 2012, but there are cost readings before and after that period. Nevertheless, despite the missing no cost data, there are still net energy readings for that period.

Here's part of the response of the `https://pge.opower.com/ei/edge/apis/DataBrowser-v1/cws/utilities/pge/utilityAccounts/XXX/reads?aggregateType=bill&includeEnhancedBilling=false&includeMultiRegisterData=false` request (which has all the readings):

```
{"startTime":"2011-10-29T00:00:00.000-07:00","endTime":"2011-11-05T00:00:00.000-07:00","consumption":{"value":0.000,"type":"ACTUAL"},"demand":null,"exported":null,"grossConsumption":null,"grossGeneration":null,"imported":null,"reactivePower":null,"providedCost":1.05,"milesDriven":0},
{"startTime":"2011-11-05T00:00:00.000-07:00","endTime":"2011-12-01T00:00:00.000-08:00","consumption":{"value":412.000,"type":"ACTUAL"},"demand":null,"exported":null,"grossConsumption":null,"grossGeneration":null,"imported":null,"reactivePower":null,"providedCost":null,"milesDriven":692},
{"startTime":"2011-12-01T00:00:00.000-08:00","endTime":"2011-12-30T00:00:00.000-08:00","consumption":{"value":680.000,"type":"ACTUAL"},"demand":null,"exported":null,"grossConsumption":null,"grossGeneration":null,"imported":null,"reactivePower":null,"providedCost":null,"milesDriven":1142},
```

It's definitely odd the data is missing. It would be a great coincidence if the cost for each of those 12 months was zero.

**Comment by tronikos** [comment] 2023-07-03 06:37
Fixed in the latest release by treating missing cost values as 0.

**Closed by tronikos** 2023-07-03 06:37 UTC
